"""
Django settings for cbt_backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.templatetags.static import static



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    #'jazzmin',
    "unfold",  # Must be BEFORE django.contrib.admin
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'cbt',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cbt.middleware.SubscriptionMiddleware',
]

ROOT_URLCONF = 'cbt_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cbt_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASES = { 
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600
    )
}

"""

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("DB_NAME", "cbt_db"),
        "USER": os.getenv("DB_USER", "exam_officer"),
        "PASSWORD": os.getenv("DB_PASSWORD", "maurice"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'versatech19@gmail.com'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')  # Your Google App Password
DEFAULT_FROM_EMAIL = 'JUST CBT <versatech19@gmail.com>'

ADMIN_EMAIL = 'olehidavis@gmail.com'
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY') 
#FRONTEND_URL = "https://cbt-frontend-taupe.vercel.app/"
FRONTEND_URL = "https://justcbt.com.ng/"
LOGIN_REDIRECT_URL = '/admin/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = os.path.join(BASE_DIR, "static")
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}



UNFOLD = {
    "SITE_TITLE": "JustCBT",
    "SITE_HEADER": "JustCBT Portal",
    "SITE_SYMBOL": "JC",
    "SITE_LOGO": lambda request: static("images/icon.png"),
    "SITE_FAVICON": lambda request: static("images/icon.png"),
    # We leave colors out of here so our CSS override takes over
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
    },
    "COLORS": {
        "primary": {
            "50": "236 253 245",
            "100": "209 250 229",
            "200": "167 243 208",
            "300": "110 231 183",
            "400": "52 211 153",
            "500": "16 185 129",
            "600": "5 150 105", # This is the main Green (Replace with your Hex converted to RGB if needed)
            "700": "4 120 87",
            "800": "6 95 70",
            "900": "4 78 56",
            "950": "2 44 34",
        },
    },
}


"""
source venv/bin/activate

superadmin = User.objects.create_superuser( username="admin001", 
email="admin@example.com",    password="winston1")

live super user :username: davisolehi, email: olehidavis@gmail.com, password: winston1

maurice123

myschool admin: my-school_admin , password winston2

from django.contrib.auth.models import User
from cbt.models import UserProfile

# Get your new admin
user = User.objects.get(username='admin')

# Create the profile (Leave school null for now if you haven't created one yet)
UserProfile.objects.create(
    user=user,
    role='superadmin',
    school=None 
)

Recommendation for Admins
Since images in Word can be tricky (sometimes they are floating or behind text), tell your admins to:

Use "In Line with Text" as the wrapping style for images.

Place the image directly below the [[[% Q %]]] tag.

postgresql://exam_officer:odcHGuE9fyuGMfF8weCxqz6W8RqM1Ts7@dpg-d4vuaj9r0fns739tblj0-a/cbt_db_iwxd
https://cbt-backend-6tdk.onrender.com
https://davisolehi.pythonanywhere.com/
https://cbt-frontend-taupe.vercel.app/
"""
